"team: medusa":
  - "@olivermrbl"
  - "@srindom"
  - "@adrien2p"
  - "@riqwan"
  - "@fPolic"
  - "@shahednasser"
  - "@carlos-r-l-rodrigues"
  - "@VariableVic"
  - "@sradevski"
  - "@thetutlage"
  - "@christiananese"
  - "@peterlgh7"
  - "@juanzgc"
